server:
  shutdown: graceful
  port: 9896

info:
  app:
    description: Job app built with Embark
    version: 1.0.0
    name: job app

management:
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
  name: firstjobapp
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/quizdb
    username: postgres
    password: hope




